In [1]:
import numpy as np

##### Create Numpy Array

In [2]:
print (np.array([2,3,4]))
#Generate empty array
print ("Empty arrays")
print (np.empty(5))
print (np.empty((5,4)))

#Generate array of 1s
print ("Array of 1s")
print (np.ones((5,4), dtype=np.int_))

#Generate an array full of random numbers, uniformly sampled from [0.0, 1.0)
print ("Random numbers - Uniform Distribution")
print (np.random.random((5, 4)))
print (np.random.rand(5, 4))
                      
#sample numbers from a Normal Distribution
print ("Random numbers - Normal Distribution")
print (np.random.normal(loc=50, scale=10, size=(2, 3)))

#Random integers
print ("Random integers")
print (np.random.randint(0, 10, size=(2, 3)))

[2 3 4]
Empty arrays
[  4.24896455e-322   0.00000000e+000   0.00000000e+000   4.46635344e-321
   0.00000000e+000]
[[  4.67296746e-307   1.69121096e-306   1.00132822e-307   9.45697982e-308]
 [  1.42419938e-306   7.56603881e-307   8.45603440e-307   2.11397635e-307]
 [  1.11261570e-306   1.29062229e-306   7.56599807e-307   8.90104239e-307]
 [  3.11525958e-307   1.69118108e-306   8.06632139e-308   1.20160711e-306]
 [  1.69119330e-306   1.29062229e-306   1.29060531e-306   2.97892385e-317]]
Array of 1s
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Random numbers - Uniform Distribution
[[ 0.68096921  0.88105383  0.2889841   0.25822149]
 [ 0.3266659   0.18423672  0.97893223  0.66999899]
 [ 0.10835649  0.76324032  0.57859886  0.63767821]
 [ 0.28677162  0.98165788  0.06183478  0.20605257]
 [ 0.68976365  0.53064481  0.2869532   0.10245263]]
[[ 0.69135584  0.58627681  0.2758608   0.19243895]
 [ 0.99176201  0.99659701  0.01357593  0.78468163]
 [ 0.30572931  0.37905137  0.22316866  0.74272

##### Array Attributes

In [3]:
a = np.random.random((5, 4))
print ("Rows:", a.shape[0])
print ("Cols:", a.shape[1])
print ("Dimention:", len(a.shape))
print ("Size:", a.size)

Rows: 5
Cols: 4
Dimention: 2
Size: 20


##### Array Operations

In [4]:
np.random.seed(693) #Seed the random number generator
a = np.random.randint(0, 10, size=(5, 4))
print ("Array:", a, sep='\n')
#axis=0: by row,  axis=1: by col
print ("Sum of all:\n", a.sum())
print ("Sum of col:\n", a.sum(axis=0))
print ("Sum of row:\n", a.sum(axis=1))
print ("Min of col:\n", a.min(axis=0))
print ("Max of row:\n", a.max(axis=1))
print ("Mean of all:\n", a.mean())

Array:
[[2 0 5 1]
 [1 3 4 4]
 [9 2 9 1]
 [9 3 7 5]
 [4 7 0 3]]
Sum of all:
 79
Sum of col:
 [25 15 25 14]
Sum of row:
 [ 8 12 21 24 14]
Min of col:
 [1 0 0 1]
Max of row:
 [5 4 9 9 7]
Mean of all:
 3.95


##### Access Array Elements By Index

In [5]:
a = np.random.rand(5)
print (a)
indices = np.array([1,1,2,3])
print (a[indices])

[ 0.31127579  0.62872047  0.07569968  0.54876981  0.53860522]
[ 0.62872047  0.62872047  0.07569968  0.54876981]


In [6]:
a = np.random.randint(0, 20, size=(5,4))
print (a)
mean =a.mean()
print ("mean: ", mean)
print (a[a<mean])

[[19  1 19  5]
 [15  7 13  5]
 [ 1 15  5  6]
 [10  8  2 10]
 [ 6  7  6 19]]
mean:  8.95
[1 5 7 5 1 5 6 8 2 6 7 6]


##### Arithmetic Operation

In [7]:
a = np.array([(1,2,3,4,5),(10,20,30,40,50)])
b = np.array([(100,200,300,400,500),(1,2,3,4,5)])
print ("Original array a:\n", a)
print ("\nMultiply a by 2:\n", a * 2)
print ("\nDivide a by 2:\n", a / 2.0)
print ("\nMultiply a and b:\n", a * b)
print ("\nDot Product a and b:", np.dot(a,np.transpose(b)))

Original array a:
 [[ 1  2  3  4  5]
 [10 20 30 40 50]]

Multiply a by 2:
 [[  2   4   6   8  10]
 [ 20  40  60  80 100]]

Divide a by 2:
 [[  0.5   1.    1.5   2.    2.5]
 [  5.   10.   15.   20.   25. ]]

Multiply a and b:
 [[ 100  400  900 1600 2500]
 [  10   40   90  160  250]]

Dot Product a and b: [[ 5500    55]
 [55000   550]]
